#
# Zabbix MCP Server
# Copyright (C) 2026 initMAX s.r.o.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

"""Prometheus-compatible /metrics endpoint for the admin portal.

Exposes a small set of operational counters / gauges / histograms in
the Prometheus text exposition format. The set is deliberately
focused on the things an SRE actually scrapes day to day:

* per-tool invocation counts split by policy decision (top-level SLO
  view: how many tool calls succeeded vs got denied vs errored)
* per-tool latency histogram (catch slow tools without grepping the
  log)
* OAuth client + token gauges (active clients, in-memory access /
  refresh tokens, recent ``client_id`` count)
* SIEM forwarder gauges (queue depth, messages sent / failed /
  dropped, connection state encoded as 0..3)
* audit log size + the housekeeping counters

No external library - pure stdlib. Format generated by hand keeps the
container slim and avoids pulling in ``prometheus_client`` (~500 KB
plus its transitive deps).
"""

from __future__ import annotations

import threading
import time
from collections import defaultdict
from typing import Any

# Latency histogram buckets, seconds. Matches the prometheus default
# (5ms - 10s) so dashboards / SLO panels carry over from any other
# Prometheus-instrumented service the operator runs.
_DEFAULT_HISTOGRAM_BUCKETS = (
    0.005, 0.01, 0.025, 0.05, 0.075,
    0.1, 0.25, 0.5, 0.75,
    1.0, 2.5, 5.0, 7.5, 10.0,
)

# Connection-state encoding for ``mcp_audit_forwarder_connection_state``:
# 0 = stopped, 1 = disconnected, 2 = connecting, 3 = connected.
_CONNECTION_STATE_VALUES = {
    "stopped": 0,
    "disconnected": 1,
    "connecting": 2,
    "connected": 3,
}


class _MetricsState:
    """Thread-safe in-memory metric storage."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        # Counters: dict[(metric_name, frozenset_of_label_pairs), int]
        self._counters: dict[tuple[str, frozenset[tuple[str, str]]], int] = defaultdict(int)
        # Histograms: dict[(metric_name, frozenset_of_label_pairs), [bucket_counts, sum, count]]
        self._histograms: dict[tuple[str, frozenset[tuple[str, str]]], dict[str, Any]] = {}
        self._buckets = _DEFAULT_HISTOGRAM_BUCKETS

    def inc_counter(self, name: str, labels: dict[str, str] | None = None, by: int = 1) -> None:
        labels = labels or {}
        key = (name, frozenset(labels.items()))
        with self._lock:
            self._counters[key] += by

    def observe(self, name: str, value: float, labels: dict[str, str] | None = None) -> None:
        labels = labels or {}
        key = (name, frozenset(labels.items()))
        with self._lock:
            entry = self._histograms.get(key)
            if entry is None:
                entry = {
                    "buckets": [0] * len(self._buckets),
                    "inf": 0,
                    "sum": 0.0,
                    "count": 0,
                }
                self._histograms[key] = entry
            for i, b in enumerate(self._buckets):
                if value <= b:
                    entry["buckets"][i] += 1
            entry["inf"] += 1
            entry["sum"] += value
            entry["count"] += 1

    def render(self, gauge_provider: callable | None = None) -> str:  # type: ignore[type-arg]
        """Return the full Prometheus exposition text.

        ``gauge_provider`` is invoked once per render; it returns a
        list of ``(name, help, value, labels)`` tuples that are
        rendered alongside the stored counters / histograms. Used for
        live state (queue depth, oauth client counts) we do not want
        to bookkeep separately.
        """
        out: list[str] = []
        with self._lock:
            counters = dict(self._counters)
            histograms = {k: {**v, "buckets": list(v["buckets"])} for k, v in self._histograms.items()}

        # --- Counters: group by metric name so HELP/TYPE appear once. ---
        by_name: dict[str, list[tuple[frozenset, int]]] = defaultdict(list)
        for (name, labels), value in counters.items():
            by_name[name].append((labels, value))
        for name, entries in sorted(by_name.items()):
            out.append(f"# HELP {name} {_HELP_TEXTS.get(name, name)}")
            out.append(f"# TYPE {name} counter")
            for labels, value in entries:
                out.append(f"{name}{_format_labels(labels)} {value}")

        # --- Histograms ---
        by_hist: dict[str, list[tuple[frozenset, dict[str, Any]]]] = defaultdict(list)
        for (name, labels), entry in histograms.items():
            by_hist[name].append((labels, entry))
        for name, entries in sorted(by_hist.items()):
            out.append(f"# HELP {name} {_HELP_TEXTS.get(name, name)}")
            out.append(f"# TYPE {name} histogram")
            for labels, entry in entries:
                for i, b in enumerate(self._buckets):
                    bucket_labels = dict(labels) | {"le": _fmt_le(b)}
                    out.append(
                        f"{name}_bucket"
                        f"{_format_labels(frozenset(bucket_labels.items()))} "
                        f"{entry['buckets'][i]}"
                    )
                inf_labels = dict(labels) | {"le": "+Inf"}
                out.append(f"{name}_bucket{_format_labels(frozenset(inf_labels.items()))} {entry['inf']}")
                out.append(f"{name}_sum{_format_labels(labels)} {entry['sum']}")
                out.append(f"{name}_count{_format_labels(labels)} {entry['count']}")

        # --- Gauges (live - read from providers, not stored) ---
        if gauge_provider is not None:
            try:
                gauges = gauge_provider() or []
            except Exception:
                gauges = []
            by_gauge: dict[str, tuple[str, list[tuple[dict, float]]]] = {}
            for name, help_text, value, labels in gauges:
                slot = by_gauge.setdefault(name, (help_text, []))
                slot[1].append((labels or {}, value))
            for name, (help_text, entries) in sorted(by_gauge.items()):
                out.append(f"# HELP {name} {help_text}")
                out.append(f"# TYPE {name} gauge")
                for labels, value in entries:
                    out.append(f"{name}{_format_labels(frozenset(labels.items()))} {value}")

        return "\n".join(out) + "\n"


_state = _MetricsState()


_HELP_TEXTS: dict[str, str] = {
    "mcp_tool_invocations_total":
        "MCP tool invocations grouped by tool name and policy decision.",
    "mcp_tool_duration_seconds":
        "Per-tool wall-clock latency, seconds.",
    "mcp_audit_rows_total":
        "Audit log rows written, grouped by category (portal / mcp_actions / background).",
    "mcp_audit_forwarder_queue_depth":
        "Current depth of the in-memory audit forwarder queue.",
    "mcp_audit_forwarder_queue_capacity":
        "Maximum depth of the in-memory audit forwarder queue.",
    "mcp_audit_forwarder_messages_sent_total":
        "Audit rows successfully shipped to the SIEM destination.",
    "mcp_audit_forwarder_messages_failed_total":
        "Audit rows that failed to ship (will retry).",
    "mcp_audit_forwarder_messages_dropped_total":
        "Audit rows dropped because the forwarder queue was full.",
    "mcp_audit_forwarder_connection_state":
        "0=stopped, 1=disconnected, 2=connecting, 3=connected.",
    "mcp_oauth_active_clients_total":
        "Number of registered OAuth clients (config-side).",
    "mcp_oauth_active_access_tokens":
        "Live OAuth access tokens held in memory.",
    "mcp_oauth_active_refresh_tokens":
        "Live OAuth refresh tokens held in memory.",
    "mcp_audit_log_size_bytes":
        "Current size of /var/log/zabbix-mcp/audit.log on disk.",
    "mcp_audit_housekeeping_archives_total":
        "Cumulative dated archives produced by the housekeeping daemon.",
    "mcp_audit_housekeeping_purged_total":
        "Cumulative archive files purged by the housekeeping daemon.",
}


def _fmt_le(b: float) -> str:
    """Bucket boundary as the canonical Prometheus string."""
    if b == int(b):
        return f"{int(b)}.0"
    return str(b)


def _esc_label(v: str) -> str:
    return v.replace("\\", "\\\\").replace("\n", "\\n").replace('"', '\\"')


def _format_labels(labels: frozenset[tuple[str, str]]) -> str:
    if not labels:
        return ""
    parts = ",".join(
        f'{k}="{_esc_label(str(v))}"'
        for k, v in sorted(labels)
    )
    return "{" + parts + "}"


# ----------------------------------------------------------------------
# Public hooks - called from server.py / audit_writer / etc.
# ----------------------------------------------------------------------


def record_tool_invocation(tool: str, decision: str, duration_seconds: float | None = None) -> None:
    """Hook from the audit emit path: count + optionally observe latency."""
    _state.inc_counter("mcp_tool_invocations_total", {"tool": tool, "decision": decision})
    if duration_seconds is not None:
        _state.observe("mcp_tool_duration_seconds", duration_seconds, {"tool": tool})


def record_audit_row(category: str) -> None:
    """Hook from audit_writer._should_emit (after the gate passes)."""
    _state.inc_counter("mcp_audit_rows_total", {"category": category})


def record_housekeeping_cycle(archives_made: int, files_purged: int) -> None:
    if archives_made:
        _state.inc_counter("mcp_audit_housekeeping_archives_total", by=archives_made)
    if files_purged:
        _state.inc_counter("mcp_audit_housekeeping_purged_total", by=files_purged)


def render() -> str:
    """Render the full Prometheus exposition text. Called by the HTTP endpoint."""
    return _state.render(gauge_provider=_collect_gauges)


def _collect_gauges() -> list[tuple[str, str, float, dict | None]]:
    """Snapshot live state into gauge tuples."""
    out: list[tuple[str, str, float, dict | None]] = []

    # SIEM forwarder live state.
    try:
        from zabbix_mcp.admin import audit_forwarder
        s = audit_forwarder.get_runtime_state()
        out.append(("mcp_audit_forwarder_queue_depth",
                    _HELP_TEXTS["mcp_audit_forwarder_queue_depth"],
                    float(s.get("queue_depth", 0)), None))
        out.append(("mcp_audit_forwarder_queue_capacity",
                    _HELP_TEXTS["mcp_audit_forwarder_queue_capacity"],
                    float(s.get("queue_size", 0)), None))
        out.append(("mcp_audit_forwarder_messages_sent_total",
                    _HELP_TEXTS["mcp_audit_forwarder_messages_sent_total"],
                    float(s.get("messages_sent", 0)), None))
        out.append(("mcp_audit_forwarder_messages_failed_total",
                    _HELP_TEXTS["mcp_audit_forwarder_messages_failed_total"],
                    float(s.get("messages_failed", 0)), None))
        out.append(("mcp_audit_forwarder_messages_dropped_total",
                    _HELP_TEXTS["mcp_audit_forwarder_messages_dropped_total"],
                    float(s.get("messages_dropped_queue_full", 0)), None))
        out.append(("mcp_audit_forwarder_connection_state",
                    _HELP_TEXTS["mcp_audit_forwarder_connection_state"],
                    float(_CONNECTION_STATE_VALUES.get(s.get("connection_state", "stopped"), 0)),
                    None))
    except Exception:
        pass

    # OAuth client / token counters - read from provider when reachable.
    try:
        from zabbix_mcp.admin.config_writer import load_config_document, TOMLKIT_AVAILABLE
        if TOMLKIT_AVAILABLE:
            # Active client count from config sections.
            try:
                from zabbix_mcp.admin.app import _ADMIN_APP_REF  # forward ref defined below
            except ImportError:
                _ADMIN_APP_REF = None
    except Exception:
        pass

    # Log size on disk.
    try:
        from zabbix_mcp.admin.audit_writer import AUDIT_LOG_PATH
        if AUDIT_LOG_PATH.exists():
            out.append(("mcp_audit_log_size_bytes",
                        _HELP_TEXTS["mcp_audit_log_size_bytes"],
                        float(AUDIT_LOG_PATH.stat().st_size), None))
    except Exception:
        pass

    return out


def collect_oauth_gauges(provider: Any) -> list[tuple[str, str, float, dict | None]]:
    """Late-binding hook the admin app calls to feed the oauth provider in."""
    out: list[tuple[str, str, float, dict | None]] = []
    if provider is None:
        return out
    try:
        access = sum(1 for _ in provider._access_tokens.values())
        refresh = sum(1 for _ in provider._refresh_tokens.values())
        out.append(("mcp_oauth_active_access_tokens",
                    _HELP_TEXTS["mcp_oauth_active_access_tokens"],
                    float(access), None))
        out.append(("mcp_oauth_active_refresh_tokens",
                    _HELP_TEXTS["mcp_oauth_active_refresh_tokens"],
                    float(refresh), None))
    except Exception:
        pass
    return out


def render_with_provider(provider: Any) -> str:
    """Render with a one-shot extra gauge provider for OAuth-side data."""
    base_gauges = _collect_gauges()
    oauth_gauges = collect_oauth_gauges(provider)
    combined = base_gauges + oauth_gauges
    return _state.render(gauge_provider=lambda: combined)
